Executing the file :

![Screenshot 2024-11-29 160146](https://github.com/user-attachments/assets/b24f9c20-9d07-454b-99e7-80d7b352fcf3)

After executing the file, gdb took control over this program

![Screenshot 2024-11-29 160317](https://github.com/user-attachments/assets/c9cbfda2-7789-4f99-b1aa-bb77262bfc72) 

![image](https://github.com/user-attachments/assets/068cecdf-ba20-4e6c-879d-0930aa674354)

We can see that there is a break point already set somewhere. 

The level's description asked us to try "c" short for "continue".

It is actually used to tell gdb to continue the program after the break point.

After using it, I got the flag.






